### ISSUE TITLE
Autocompletion (Tab)

### ISSUE THREAD

**Issue by crysis992** [xChris6041x/Devin#1]
Hey,

I've made a simple teleport command using this framework, I noticed that the autocompletion of player names does not work when using any command made with this framework.

Example:
`	@Command(struct = "tp", params = { "Player", "Player" }, perms = "ct.tp")
	public CommandResult teleport(Player sender, Player target, @OptionalArg Player target2) {

		if (target2 == null) {
			sender.sendMessage(F.main("§eTeleport", "Teleporting to " + target.getName()));
			sender.teleport(target, TeleportCause.COMMAND);
			UtilPlayer.playSound(sender, Sound.ENTITY_ENDERMEN_TELEPORT);
			return CommandResult.success();
		} else {
			sender.sendMessage(F.main("§eTeleport", "Teleporting " + target.getName() + " to " + target2.getName()));
			UtilPlayer.playSound(target, Sound.ENTITY_ENDERMEN_TELEPORT);
			target.teleport(target2, TeleportCause.COMMAND);
			return CommandResult.success();
		}
	}`

When entering /tp cry and then pressing the tab button it should auto-complete to crysis992, but that does not happen. My players and staff is used to the tab completion method.

Also, is there any way to add a custom tabcompletion? I would like to print a list of avaiable homes when entering /home and pressing tab after that, or autocomplete avaiable homes starting with the written character.

**Comment by xChris6041x** [comment]
I apologize for the delay. I am getting back into developing this after not being able to use my PC. The plan for phase two of auto completion is to have player names and enum support.

Having a custom list for auto completion is a great idea and I will look into possible ways to add this to the library.

**Comment by xChris6041x** [comment]
There is a fix on the development branch, but still needs some work.

**Comment by xChris6041x** [comment]
All issues have been resolved and merged into master and the feature idea has moved to a new issue.
