### ISSUE TITLE
Invalid Command broadcasted to all players

### ISSUE THREAD

**Issue by crysis992** [xChris6041x/Devin#3]
When using a command struct with a space and just typing the first argument, it causes a "Invalid Command <command>" error message. But this message is broadcasted to all online players, instead of the player that issued the command.

Example:
@Command(struct = "test add", params = { "regionID", "faction", "name" }, perms = "ct.test")
public CommandResult testMethod(Player sender, String region, String faction, ArgumentStream args) {
		return CommandResult.success();
	}

When typing just /test it broadcasts "Invalid Command test" to all online players.
Expected result: It should just broadcast the error message to the command sender.

**Comment by Helmare** [comment]
This issue has been fixed on the development branch. Looking to get an updated jar later today.
