### ISSUE TITLE
Registering same permission for multiple commands

### ISSUE THREAD

**Issue by crysis992** [xChris6041x/Devin#4]
When registering multiple commands with the same permission Bukkit throws an error that the permission is already registered.

I sadly don't know how to make Pull Requests but here is the fix:

Changing following:
`                for (String perm : cmd.perms()) {
                    Bukkit.getPluginManager().addPermission(new Permission(perm));
                    Devin.debug("\t\tRegistered permission " + AnsiColor.CYAN + perm + AnsiColor.RESET + " /w Spigot");
                }`

to this will fix the issue.
Simply checking if the permission doesnt exist already before trying to add it.

`				for (String perm : cmd.perms()) {
					if (Bukkit.getPluginManager().getPermission(perm) == null) {
						Bukkit.getPluginManager().addPermission(new Permission(perm));
						Devin.debug("\t\tRegistered permission " + AnsiColor.CYAN + perm + AnsiColor.RESET + " /w Spigot");
					}
				}`

**Comment by Helmare** [comment]
This issue has been fixed on the development branch.
